ckpt_path: weights/vqvae_32000_tokens_p3_mass_pid/model_ckpt.ckpt
# ckpt_path: /home/laurits/ml-tau-en-reg/enreg/omnijet_alpha/gabbro/checkpoints/vqvae_32000_tokens_p3_mass_pid/model_ckpt.ckpt
bb_path: weights/OmniJet_generative_model_FiduciaryCagoule_254.ckpt
# bb_path: /home/laurits/ml-tau-en-reg/enreg/omnijet_alpha/gabbro/checkpoints/generative_32000_tokens_p4_mass_pid/OmniJet_generative_model_FiduciaryCagoule_254.ckpt
num_rounds_frozen_backbone: 0
version: "fixed_backbone"
versions:
    - "from_scratch"
    - "fixed_backbone"
    - "fine_tuning"
hyperparameters:
    num_layers: 2
    embed_dims:
        - 256
        - 512
        - 256
defaults:
    - _self_
