dataset:
  max_cands: 25
  use_pdgId: True
  min_jet_theta: 0.0
  max_jet_theta: 1.0e+3
  min_jet_pt: 0.0
  max_jet_pt: 1.0e+3
  # n_class: 2
  n_hidden: 72
  dropout: 0.2
  n_layers: 6
  c_weight: 0.005
  beams:
    add: True
    mass: 1.0
  one_hot_encoding:
    cand_px: False
    cand_py: False
    cand_pz: False
    cand_en: False
    cand_charge: False
    isElectron: True
    isMuon: True
    isPhoton: True
    isChargedHadron: True
    isNeutralHadron: True
    isProton: True
    pad: False