dataset_class: LorentzNetDataset
num_classes:
  dm_multiclass: 16
  jet_regression: 1
  binary_classification: 2
feature_standardization:
  standardize_inputs: False
  method: median_quantile
  path: /home/laurits/ml-tau-en-reg/enreg/data/LorentzNet_FeatureStandardization.json
defaults:
  - training
  - dataset
  - lrfinder
  - builder