training:
  type: regression # Or classification
  model_file: LorentzNet_model.pt
  # n_class: 2
  num_epochs: 350
  n_hidden: 72
  dropout: 0.2
  n_layers: 6
  c_weight: 0.005
  batch_size: 512
  num_dataloader_workers: 4
  classweight_sig: 1
  classweight_bgr: 10
  use_class_weights: True
  use_per_jet_weights: True
  use_focal_loss: True
  focal_loss_gamma: 2.0
  verbosity: 1
