output_dir: /home/laurits/tmp/20240303_hjolmberg2022_jet_metrics
plot_samples_separately: True
gen_E_type: gen_vis_tau_E
load_from_json: False
comparison_datasets:
  - test
comparison_samples:
  - ZH_Htautau
  - Z_Ztautau
n_comparison_files: -1
defaults:
  - metrics: metrics
  - _self_