output_dir: /home/norman/ENREG/metrics/240424_PT_LN_SDNN
plot_samples_separately: True
load_from_json: False
comparison_datasets:
  - test
comparison_samples:
  - ZH_Htautau
  - Z_Ztautau
n_comparison_files: -1
defaults:
  - metrics: metrics
  - _self_