output_dir: outputs/regression_plots
plot_samples_separately: True
load_from_json: False

#this path contains the input ntuples to the ML model (jet & tau properties)
#the model predictions are stored in separte files
#and are configured in metrics/regression.yaml -> algorithms/ntuples_dir
base_ntuple_path: /scratch/persistent/joosep/ml-tau/20240701_lowered_ptcut_merged
comparison_samples:
  - zh_test
  - z_test

defaults:
  - metrics: metrics
  - _self_
