directories:
  OUTPUT_DIR: 'ml-tau-en-reg/notebooks/z_temp_output/'
  # BASE_DATA_DIR: "/scratch/persistent/laurits/ml-tau/20241002_Training_ntuples_geq20gev"
  # BASE_TRAINING_DIR: '/home/laurits/ml-tau-en-reg/training-outputs'
  BASE_DATA_DIR: '/home/hardi/Doc/pyfailid/ml-tau-en-reg/20241002_Training_ntuples_geq20ge'
  BASE_TRAINING_DIR: '/home/hardi/Doc/pyfailid/ml-tau-en-reg/training-outputs'

training_data:
    # - z_train
    # - zh_train
    # - qq_train
    # - z_test
    - zh_test
    # - qq_test

evaluating:
  training_types:
    - '20201204_ParT_ntrain_v2'
    - '20250113_OmniParT_fine_tuning_freeze_60'
    # - '20201206_updated_DM_training'
    # - '20201211_ParT_no_PMHA'
    # - '20241220_unfreeze_from_start'
    # - '20241204_ParT_ntrain'
    # - '20250109_OmniParT_2GPT_layers'
  model_types:
    version:
      - 'v1'
      # - 'v2'
      # - 'v3'
    train_frac:
      - 'trainfrac_1e4'
      # - 'trainfrac_1e5'
      # - 'trainfrac_1e6'
      # - 'trainfrac_2e3'
    tasks:
      - 'jet_regression'
      - 'dm_multiclass'
      - 'binary_classification'
      # - 'tagger'
    models:
      - 'ParticleTransformer'
      # - 'LorentzNet'
      # - 'DeepSet'
      # - 'HPS'
      # - 'OmniParT_from_scratch'
      - 'OmniParT_fine_tuning'
      # - 'OmniParT_fixed_backbone'
    z_OR_zh_test:
      # - 'z_test'
      - 'zh_test'
