relative_sizes:
  train: 0.7
  test: 0.2
  validation: 0.1
datasets:
  zh:
    title: "ee $\\rightarrow$ ZH (H $\\rightarrow \\tau\\tau$)"
    x_max: 170
  z:
    title: "ee $\\rightarrow$ Z (Z $\\rightarrow \\tau\\tau$)"
    x_max: 190
defaults:
  - ntupelizer
  - _self_