verbosity: 1
n_files: -1
output_dir: /home/joosep/ENREG/training/240514_tests
training_type: dm_multiclass
# training_type: energy_regression
# training_type: binary_classification
model_type: ParticleTransformer
data_path: /home/joosep/ml-tau-en-reg/data/

samples_to_use:
  - ZH_Htautau
  # - Z_Ztautau
  # - QCD
defaults:
  - models: models
  - datasets: datasets
  - tau_builder
  - ntupelizer
  - _self_
