verbosity: 1
n_files: 10
output_dir: /home/norman/ENREG/training/240507_PT_test
samples_to_use:
  - ZH_Htautau
  # - Z_Ztautau
  # - QCD
defaults:
  - models: models
  - datasets: datasets
  - tau_builder
  - ntupelizer
  - _self_