verbosity: 1

#everything that the user should modify is here
output_dir: /home/joosep/ml-tau-en-reg/training-outputs/240515_fullstats/
data_path: /home/joosep/ml-tau-en-reg/data/20240402_full_stats_merged/

training_type: dm_multiclass
# training_type: energy_regression
# training_type: binary_classification

model_type: ParticleTransformer
# model_type: LorentzNet
# model_type: SimpleDNN

training_samples:
  - zh_train.parquet
#  - qq_train.parquet

test_samples:
  - zh_test.parquet
  - z_test.parquet
#  - qq_test.parquet

#the training sample will be further subdividied as follows
fraction_train: 0.05
fraction_valid: 0.05

defaults:
  - models: models
  - tau_builder
  - ntupelizer
  - _self_
