verbosity: 1
output_dir: /home/laurits/240303_holmberg2022jet_target
samples_to_use:
  - ZH_Htautau
  # - Z_Ztautau # As there are no Z_Ztautau files in the training dataset
defaults:
  - models: models
  - datasets: datasets
  - tau_builder
  - ntupelizer
  - _self_