verbosity: 1
n_files: -1
output_dir: /home/joosep/ENREG/training/240514_SDNN_DM_improved
samples_to_use:
  - ZH_Htautau
  # - Z_Ztautau
  # - QCD
defaults:
  - models: models
  - datasets: datasets
  - tau_builder
  - ntupelizer
  - _self_
