verbosity: 1
n_files: -1
output_dir: /home/laurits/ENREG/training/20240410_PT_training/
samples_to_use:
  - ZH_Htautau
  - Z_Ztautau
  # - QCD
defaults:
  - models: models
  - datasets: datasets
  - tau_builder
  - ntupelizer
  - _self_