verbosity: 1
n_files: -1
output_dir: /home/norman/ENREG/training/240508_LN_DM
samples_to_use:
  - ZH_Htautau
  # - Z_Ztautau
  # - QCD
defaults:
  - models: models
  - datasets: datasets
  - tau_builder
  - ntupelizer
  - _self_