use_slurm: True
use_multiprocessing: True
tree_path: events
branches:
  - MCParticles
  - MergedRecoParticles
  - SiTracks_Refitted_1
  - PrimaryVertices
test_run: False
samples_to_process:
  - Z_Ztautau
  - ZH_Htautau-xyz
  - QCD
samples:
  Z_Ztautau:
    input_dir: /foo/bar
    output_dir: /scratch/persistent/laurits/ml-tau-ntupelized-data/CLIC_data_20230925/Z_Ztautau
  ZH_Htautau:
    input_dir: /foo/bar
    output_dir: /scratch/persistent/laurits/ml-tau-ntupelized-data/CLIC_data_20230525/ZH_Htautau
  QCD:
    input_dir: /foo/bar
    output_dir: /scratch/persistent/laurits/ml-tau-ntupelized-data/CLIC_data_20230525/QCD
validation:
  output_dir: $HOME/CLIC_ntuple_validation_v5
  validation_samples:
    - Z_Ztautau
    - ZH_Htautau
    - QCD