slurm_run: False
files_per_job: 20
n_files: -1
tree_path: events
branches:
  - MCParticles.PDG
  - MCParticles.generatorStatus
  - MCParticles.simulatorStatus
  - MCParticles.charge
  - MCParticles.time
  - MCParticles.mass
  - MCParticles.vertex.x
  - MCParticles.vertex.y
  - MCParticles.vertex.z
  - MCParticles.endpoint.x
  - MCParticles.endpoint.y
  - MCParticles.endpoint.z
  - MCParticles.momentum.x
  - MCParticles.momentum.y
  - MCParticles.momentum.z
  - MCParticles.momentumAtEndpoint.x
  - MCParticles.momentumAtEndpoint.y
  - MCParticles.momentumAtEndpoint.z
  - MCParticles.spin.x
  - MCParticles.spin.y
  - MCParticles.spin.z
  - MCParticles.parents_begin
  - MCParticles.parents_end
  - MCParticles.daughters_begin
  - MCParticles.daughters_end
  - PandoraPFOs.PDG
  - PandoraPFOs.energy
  - PandoraPFOs.momentum.x
  - PandoraPFOs.momentum.y
  - PandoraPFOs.momentum.z
  - PandoraPFOs.referencePoint.x
  - PandoraPFOs.referencePoint.y
  - PandoraPFOs.referencePoint.z
  - PandoraPFOs.charge
  - PandoraPFOs.mass
  - PandoraPFOs.goodnessOfPID
  - PandoraPFOs.covMatrix.values[10]
  - PandoraPFOs.clusters_begin
  - PandoraPFOs.clusters_end
  - PandoraPFOs.tracks_begin
  - PandoraPFOs.tracks_end
  - PandoraPFOs.particles_begin
  - PandoraPFOs.particles_end
  - SiTracks_Refitted.type
  - SiTracks_Refitted.chi2
  - SiTracks_Refitted.ndf
  - SiTracks_Refitted.Nholes
  - SiTracks_Refitted.subdetectorHitNumbers_begin
  - SiTracks_Refitted.subdetectorHitNumbers_end
  - SiTracks_Refitted.subdetectorHoleNumbers_begin
  - SiTracks_Refitted.subdetectorHoleNumbers_end
  - SiTracks_Refitted.trackStates_begin
  - SiTracks_Refitted.trackStates_end
  - SiTracks_Refitted.trackerHits_begin
  - SiTracks_Refitted.trackerHits_end
  - SiTracks_Refitted.tracks_begin
  - SiTracks_Refitted.tracks_end
  - PrimaryVertices.type
  - PrimaryVertices.chi2
  - PrimaryVertices.ndf
  - PrimaryVertices.position.x
  - PrimaryVertices.position.y
  - PrimaryVertices.position.z
  - PrimaryVertices.covMatrix.values[6]
  - PrimaryVertices.algorithmType
  - PrimaryVertices.parameters_begin
  - PrimaryVertices.parameters_end
  - PrimaryVertices.particles_begin
  - PrimaryVertices.particles_end
  - _SiTracks_Refitted_trackStates.location
  - _SiTracks_Refitted_trackStates.D0
  - _SiTracks_Refitted_trackStates.phi
  - _SiTracks_Refitted_trackStates.omega
  - _SiTracks_Refitted_trackStates.Z0
  - _SiTracks_Refitted_trackStates.tanLambda
  - _SiTracks_Refitted_trackStates.time
  - _SiTracks_Refitted_trackStates.referencePoint.x
  - _SiTracks_Refitted_trackStates.referencePoint.y
  - _SiTracks_Refitted_trackStates.referencePoint.z
  - _SiTracks_Refitted_trackStates.covMatrix.values[21]
  - _MCParticles_daughters/_MCParticles_daughters.index
  # - _RecoMCTruthLink_from.index
  # - _RecoMCTruthLink_to.index
  # - _PandoraPFOs_tracks.index
  # - idx_reco
  # - idx_mc
  # - idx_track
  # - _MCParticles_daughters.index
samples_to_process:
  # - p8_ee_ZH_Htautau_ecm365
  # - p8_ee_ZH_Htautau_ecm240
  # - p8_ee_ZZ_tautau_ecm365
  # - p8_ee_qq_ecm365
  - p8_ee_Z_tautau_ecm91
  # - p8_ee_Z_qq_ecm91
samples:
  # p8_ee_ZH_Htautau_ecm365:
  #   input_dir: /local/joosep/mlpf/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/gen/p8_ee_ZH_Htautau_ecm365/
  #   output_dir: /local/norman/ml-tau/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/p8_ee_ZH_Htautau_ecm365/
  #   is_signal: True
  # p8_ee_ZZ_tautau_ecm365:
  #   input_dir: /local/joosep/mlpf/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/gen/p8_ee_ZZ_tautau_ecm365/
  #   output_dir: /local/norman/ml-tau/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/p8_ee_ZZ_tautau_ecm365/
  #   is_signal: True
  # p8_ee_qq_ecm365:
  #   input_dir: /local/joosep/mlpf/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/gen/p8_ee_qq_ecm365/
  #   output_dir: /local/norman/ml-tau/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/p8_ee_qq_ecm365/
  #   is_signal: False
  p8_ee_Z_tautau_ecm91:
    input_dir: /local/joosep/mlpf/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/gen/p8_ee_Z_tautau_ecm91/
    output_dir: /local/norman/ml-tau/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/p8_ee_Z_tautau_ecm91/
    is_signal: True
  # p8_ee_Z_qq_ecm91:
  #   input_dir: /local/joosep/mlpf/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/gen/p8_ee_Z_qq_ecm91/
  #   output_dir: /local/norman/ml-tau/cld/v1.2.3_key4hep_2025-05-29_CLD_f1e8f9/p8_ee_Z_qq_ecm91/
  #   is_signal: False
# validation:
#   output_dir: $HOME/CLIC_ntuple_validation
#   validation_samples:
#     - p8_ee_ZH_Htautau_ecm240
#     - p8_ee_ZZ_tautau_ecm365
