slurm_run: False
files_per_job: 20
n_files: -1
tree_path: events
branches:
  - MCParticles.PDG
  - MCParticles.generatorStatus
  - MCParticles.charge
  - MCParticles.mass
  - MCParticles.vertex.x
  - MCParticles.vertex.y
  - MCParticles.vertex.z
  - MCParticles.momentum.x
  - MCParticles.momentum.y
  - MCParticles.momentum.z
  - MCParticles.parents_begin
  - MCParticles.parents_end
  - MCParticles.daughters_begin
  - MCParticles.daughters_end
  - MergedRecoParticles.type
  - MergedRecoParticles.energy
  - MergedRecoParticles.momentum.x
  - MergedRecoParticles.momentum.y
  - MergedRecoParticles.momentum.z
  - MergedRecoParticles.referencePoint.x
  - MergedRecoParticles.referencePoint.y
  - MergedRecoParticles.referencePoint.z
  - MergedRecoParticles.charge
  - MergedRecoParticles.mass
  - MergedRecoParticles.goodnessOfPID
  - MergedRecoParticles.covMatrix[10]
  - MergedRecoParticles.clusters_begin
  - MergedRecoParticles.clusters_end
  - MergedRecoParticles.tracks_begin
  - MergedRecoParticles.tracks_end
  - MergedRecoParticles.particles_begin
  - MergedRecoParticles.particles_end
  - MergedRecoParticles.particleIDs_begin
  - MergedRecoParticles.particleIDs_end
  - PrimaryVertices.position.x
  - PrimaryVertices.position.y
  - PrimaryVertices.position.z
  - SiTracks_Refitted_1.location
  - SiTracks_Refitted_1.referencePoint.x
  - SiTracks_Refitted_1.referencePoint.y
  - SiTracks_Refitted_1.referencePoint.z
  - SiTracks_Refitted_1.D0
  - SiTracks_Refitted_1.Z0
  - SiTracks_Refitted_1.phi
  - SiTracks_Refitted_1.tanLambda
  - SiTracks_Refitted_1.omega
  - SiTracks_Refitted_1.covMatrix[21]
samples_to_process:
  - p8_ee_Z_Ztautau_ecm380
  - p8_ee_ZH_Htautau_ecm380
  - p8_ee_qq_ecm380
samples:
  p8_ee_Z_Ztautau_ecm380:
    input_dir: /local/joosep/clic_edm4hep/2024_07/p8_ee_Z_Ztautau_ecm380/
    output_dir: /local/laurits/ml-tau-en-reg/ntuples/20240924_lowered_recoPtCut/p8_ee_Z_Ztautau_ecm380/
    is_signal: True
  p8_ee_ZH_Htautau_ecm380:
    input_dir: /local/joosep/clic_edm4hep/2024_07/p8_ee_ZH_Htautau_ecm380/
    output_dir: /local/laurits/ml-tau-en-reg/ntuples/20240924_lowered_recoPtCut/p8_ee_ZH_Htautau_ecm380/
    is_signal: True
  p8_ee_qq_ecm380:
    input_dir: /local/joosep/clic_edm4hep/2024_07/p8_ee_qq_ecm380/
    output_dir: /local/laurits/ml-tau-en-reg/ntuples/20240924_lowered_recoPtCut/p8_ee_qq_ecm380/
    is_signal: False
validation:
  output_dir: $HOME/CLIC_ntuple_validation
  validation_samples:
    - p8_ee_Z_Ztautau_ecm380 
    - p8_ee_ZH_Htautau_ecm380 
    - p8_ee_qq_ecm380 
