builder: ParticleTransformer
output_dir: /scratch/persistent/laurits/test
n_files: 1
use_slurm: False
verbosity: 0
use_multiprocessing: False
datasets_to_process:
  - test
  - train
  - validation
samples_to_process:
  - ZH_Htautau
  - Z_Ztautau
  - QCD
defaults:
  - datasets: datasets
  - models: models
  - ntupelizer
  - _self_