builder: LorentzNet #ParticleTransformer #HPS
builder_task: dm_multiclass #regression
output_dir: /home/norman/ENREG/ntuples/240508_LN_DM
PT_tauID_ntuple_dir: /scratch/persistent/laurits/PT_tauID_ntuples
n_files: -1
slurm_run: False
verbosity: 0
use_multiprocessing: False
use_slurm: True
datasets_to_process:
  - test
  # - train
  # - validation
samples_to_process:
  - ZH_Htautau
  - Z_Ztautau
defaults:
  - datasets: datasets
  - models: models
  - ntupelizer
  - _self_