builder: HPS
builder_task: regression  # or classification
output_dir: /scratch/persistent/laurits/20240302_Initial_run
PT_tauID_ntuple_dir: /scratch/persistent/laurits/PT_tauID_ntuples
n_files: -1
slurm_run: False
verbosity: 0
use_multiprocessing: True
use_slurm: False
datasets_to_process:
  - test
  - train
  - validation
samples_to_process:
  - ZH_Htautau
  - Z_Ztautau
  # - QCD  # As we are interested only in the reconstruction of tau and not in the ID, the QCD not needed
defaults:
  - datasets: datasets
  - models: models
  - ntupelizer
  - _self_