dm_reconstruction:
    base_dir: /home/laurits/ml-tau-en-reg/training-outputs/20201204_ParT_ntrain_v2/v1/trainfrac_1e4/dm_multiclass
    algorithms:
        ParticleTransformer:
            data_dir: ${dm_reconstruction.base_dir}

defaults:
    - _self_
