regression:
  ratio_plot:
    bin_edges:
      zh_test: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175]
      z_test: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200]
  cls_wp: Tight
  classifier_WPs:  # The values for ParticleTransformer from the previous paper
      Loose: 0.930
      Medium: 0.967
      Tight: 0.975
  algorithms:
    ParticleTransformer:
      ntuples_dir: /local/joosep/ml-tau-en-reg/results/240524_cosinescheduler/jet_regression/ParticleTransformer/
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "//"
      color: "tab:purple"
    LorentzNet:
      ntuples_dir: /local/joosep/ml-tau-en-reg/results/240524_cosinescheduler/jet_regression/LorentzNet/
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "//"
      color: "tab:green"
    SimpleDNN:
      ntuples_dir: /local/joosep/ml-tau-en-reg/results/240524_cosinescheduler/jet_regression/SimpleDNN/
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "//"
      color: "black"

defaults:
  - _self_
