regression:
  ratio_plot:
    bin_edges: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200]
  cls_wp: Tight
  classifier_WPs:  # The values for ParticleTransformer from the previous paper
      Loose: 0.930
      Medium: 0.967
      Tight: 0.975
  algorithms:
    ParticleTransformer:
      ntuples_dir: /home/laurits/ENREG/training/20240403_PT_full_stats_ZH_plus_Z_regression_no_lifetme/ParticleTransformer
      json_metrics_path: /home/laurits/tmp/20240228_enreg_metrics_test/plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "//"
      color: "tab:purple"
    LorentzNet:
      ntuples_dir: /home/laurits/ENREG/ntuples/20240409_LorentzNet/LorentzNet
      json_metrics_path: /home/laurits/tmp/20240228_enreg_metrics_test/plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "//"
      color: "tab:green"
    SimpleDNN:
      ntuples_dir: /home/laurits/ENREG/ntuples/20240415_SimpleDNN/SimpleDNN
      json_metrics_path: /home/laurits/tmp/20240228_enreg_metrics_test/plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "//"
      color: "black"
    HPS:
      ntuples_dir: /home/laurits/ENREG/ntuples/2024013_HPS_HEPMC_ntuples/HPS
      json_metrics_path: /home/laurits/tmp/20240228_enreg_metrics_test/plotting_data.json
      load_from_json: False
      compare: False
      marker: "o"
      hatch: '\\\\'
      color: "tab:blue"

defaults:
  - _self_