regression:
    base_dir: /home/laurits/ml-tau-en-reg/training-outputs/20201204_ParT_ntrain_v2/v1/trainfrac_1e4/jet_regression
    algorithms:
        ParticleTransformer:
            data_dir: ${regression.base_dir}
    ratio_plot:
        bin_edges:
            zh: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175]
            z: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200]
        resolution_plot:
            ylabel: "$p_T\\ resol.\\ (q_{75} - q_{25})/q_{50}$"
            ylim: [0, 0.06]
            xlabel: "$p_T^{gen}$"
            xscale: "linear"
            yscale: "linear"
            nticks: 7
        response_plot:
            ylabel: "$p_T\\ scale\\ (q_{50})$"
            ylim: [0.99, 1.01]
            xlabel: "$p_T^{gen}$"
            xscale: "linear"
            yscale: "linear"
            nticks: 3

defaults:
    - _self_
