regression:
  ratio_plot:
    bin_edges:
      zh: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175]
      z: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200]
    resolution_plot:
      ylabel: "$p_T\\ resol.\\ (q_{75} - q_{25})/q_{50}$"
      ylim: [0, 0.1]
      xlabel: "$p_T^{gen}$"
      xscale: "linear"
      yscale: "log"
    response_plot:
      ylabel: "$p_T\\ scale\\ (q_{50})$"
      ylim: [0.96, 1.04]
      xlabel: "$p_T^{gen}$"
      xscale: "linear"
      yscale: "log"
  algorithms:
    DeepSet:
      ntuples_dir: /path/to/files
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "*"
      hatch: "//"
      color: "tab:purple"

defaults:
  - _self_
