regression:
  ratio_plot:
    bin_edges:
      zh_test: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175]
      z_test: [20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200]
  cls_wp: Tight
  classifier_WPs:  # The values for ParticleTransformer from the previous paper
      Loose: 0.930
      Medium: 0.967
      Tight: 0.975
  algorithms:
    ParticleTransformer:
      ntuples_dir: /home/laurits/ml-tau-en-reg/training-outputs/20240701_lowered_ptcut_merged/v1/jet_regression/ParticleTransformer/
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "*"
      hatch: "//"
      color: "tab:purple"
    LorentzNet:
      ntuples_dir: /home/laurits/ml-tau-en-reg/training-outputs/20240701_lowered_ptcut_merged/v1/jet_regression/LorentzNet/
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "D"
      hatch: "\\\\"
      color: "tab:green"
    DeepSet:
      ntuples_dir: /home/laurits/ml-tau-en-reg/training-outputs/20240701_lowered_ptcut_merged/v1/jet_regression/SimpleDNN/
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "v"
      hatch: "."
      color: "black"
    OmniParT:
      ntuples_dir: /home/laurits/ml-tau-en-reg/training-outputs/240718_OmniParT/v1/jet_regression/OmniParT
      json_metrics_path: plotting_data.json
      load_from_json: False
      compare: True
      marker: "^"
      hatch: "||"
      color: "blue"

defaults:
  - _self_
