builder:
  metric: "theta-phi" # dataset.yaml sees kas see - kus ja miks vaja kasutada
  # model_path: /home/laurits/ml-tau-en-reg/enreg/data/ParticleTransformer_model_wLifetime_2023Jun22.pt #  PT classifier
  model_path: /home/laurits/240303_holmberg2022jet_target/ParticleTransformer_model_best.pt  # regression
