dataset:
  max_cands: 25
  use_pdgId: True
  use_lifetime: True
  # metric: eta-phi
  min_jet_theta: 0.0
  max_jet_theta: 1000
  min_jet_pt: 0
  max_jet_pt: 1000
  one_hot_encoding:
    cand_deta: False
    cand_dphi: False
    cand_logpt: False
    cand_loge: False
    cand_logptrel: False
    cand_logerel: False
    cand_deltaR: False
    cand_charge: False
    isElectron: True
    isMuon: True
    isPhoton: True
    isChargedHadron: True
    isNeutralHadron: True
    cand_d0: False
    cand_d0_err: False
    cand_dz: False
    cand_dz_err: False
    cand_px: False
    cand_py: False
    cand_pz: False
    cand_en: False