feature_standardization:
  standardize_inputs: False
  method: "mean_rms"
  path: /home/laurits/ml-tau-en-reg/enreg/data/ParticleTransformer_FeatureStandardization.json
defaults:
  - builder
  - dataset
  - lrfinder
  - training