training:
  type: dm_multiclass #regression # Or classification
  model_file: ParticleTransformer_model.pt  # sync with builder
  batch_size: 512
  num_epochs: 100
  num_dataloader_workers: 6
  classweight_sig: 1
  classweight_bgr: 10
  use_class_weights: True
  use_per_jet_weights: True
  use_focal_loss: True
  focal_loss_gamma: 2.0
  fast_optimizer: AdamW # Or RAdam
  slow_optimizer: None # Or Lookahead
  verbosity: 1  # Sync with main training
