builder:
  task: "dm_multiclass" #"regression" 
  regression:
    model_path: /home/norman/ENREG/training/240503_SDNN_DM/SimpleDNN_model_best.pt
  dm_multiclass:
    model_path: /home/norman/ENREG/training/240503_SDNN_DM/SimpleDNN_model_best.pt