samples:
  p8_ee_Z_Ztautau_ecm380:
    input_dir: /local/joosep/clic_edm4hep/2024_07/p8_ee_Z_Ztautau_ecm380/
    output_dir: /local/laurits/ml-tau-en-reg/ntuples/20241001_drop_pyhepmc_FULL/p8_ee_Z_Ztautau_ecm380/
    is_signal: True
  p8_ee_ZH_Htautau_ecm380:
    input_dir: /local/joosep/clic_edm4hep/2024_07/p8_ee_ZH_Htautau_ecm380/
    output_dir: /local/laurits/ml-tau-en-reg/ntuples/20241001_drop_pyhepmc_FULL/p8_ee_ZH_Htautau_ecm380/
    is_signal: True
  p8_ee_qq_ecm380:
    input_dir: /local/joosep/clic_edm4hep/2024_07/p8_ee_qq_ecm380/
    output_dir: /local/laurits/ml-tau-en-reg/ntuples/20241001_drop_pyhepmc_FULL/p8_ee_qq_ecm380/
    is_signal: False