test:
  ZH_Htautau:
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200201.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200202.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200203.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200204.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200205.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200206.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200207.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200208.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200209.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200210.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200211.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200212.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200213.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200214.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200215.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200216.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200217.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200218.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200219.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200220.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200221.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200222.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200223.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200224.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200225.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200226.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200227.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200228.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200229.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200230.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200231.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200232.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200233.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200234.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200235.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200236.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200237.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200238.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200239.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200240.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200241.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200242.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200243.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200244.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200245.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200246.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200247.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200248.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200249.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200250.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200251.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200252.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200253.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200254.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200255.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200256.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200257.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200258.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200259.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200260.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200261.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200262.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200263.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200264.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200265.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200266.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200267.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200268.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200269.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200270.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200271.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200272.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200273.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200274.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200275.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200276.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200277.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200278.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200279.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200280.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200281.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200282.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200283.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200284.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200285.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200286.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200287.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200288.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200289.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200290.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200291.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200292.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200293.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200294.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200295.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200296.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200297.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200298.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200299.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200300.parquet
  QCD:
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100201.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100202.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100203.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100204.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100205.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100206.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100207.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100208.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100209.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100210.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100211.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100212.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100213.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100214.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100215.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100216.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100217.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100218.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100219.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100220.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100221.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100222.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100223.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100224.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100225.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100226.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100227.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100228.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100229.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100230.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100231.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100232.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100233.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100234.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100235.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100236.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100237.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100238.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100239.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100240.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100241.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100242.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100243.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100244.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100245.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100246.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100247.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100248.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100249.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100250.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100251.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100252.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100253.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100254.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100255.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100256.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100257.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100258.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100259.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100260.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100261.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100262.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100263.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100264.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100265.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100266.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100267.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100268.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100269.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100270.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100271.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100272.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100273.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100274.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100275.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100276.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100277.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100278.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100279.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100280.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100281.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100282.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100283.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100284.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100285.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100286.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100287.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100288.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100289.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100290.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100291.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100292.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100293.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100294.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100295.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100296.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100297.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100298.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100299.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100300.parquet
