train:
  ZH_Htautau:
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200001.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200002.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200003.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200004.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200005.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200006.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200007.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200008.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200009.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200010.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200011.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200012.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200013.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200014.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200015.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200016.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200017.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200018.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200019.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200020.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200021.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200022.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200023.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200024.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200025.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200026.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200027.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200028.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200029.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200030.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200031.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200032.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200033.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200034.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200035.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200036.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200037.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200038.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200039.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200040.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200041.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200042.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200043.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200044.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200045.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200046.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200047.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200048.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200049.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200050.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200051.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200052.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200053.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200054.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200055.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200056.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200057.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200058.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200059.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200060.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200061.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200062.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200063.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200064.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200065.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200066.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200067.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200068.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200069.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200070.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200071.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200072.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200073.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200074.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200075.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200076.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200077.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200078.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200079.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200080.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200081.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200082.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200083.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200084.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200085.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200086.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200087.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200088.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200089.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200090.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200091.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200092.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200093.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200094.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200095.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200096.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200097.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200098.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200099.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200100.parquet
  QCD:
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100001.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100002.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100003.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100004.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100005.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100006.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100007.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100008.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100009.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100010.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100011.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100012.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100013.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100014.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100015.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100016.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100017.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100018.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100019.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100020.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100021.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100022.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100023.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100024.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100025.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100026.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100027.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100028.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100029.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100030.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100031.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100032.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100033.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100034.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100035.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100036.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100037.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100038.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100039.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100040.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100041.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100042.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100043.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100044.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100045.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100046.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100047.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100048.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100049.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100050.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100051.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100052.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100053.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100054.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100055.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100056.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100057.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100058.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100059.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100060.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100061.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100062.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100063.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100064.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100065.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100066.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100067.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100068.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100069.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100070.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100071.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100072.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100073.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100074.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100075.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100076.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100077.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100078.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100079.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100080.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100081.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100082.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100083.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100084.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100085.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100086.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100087.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100088.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100089.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100090.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100091.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100092.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100093.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100094.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100095.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100096.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100097.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100098.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100099.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100100.parquet
