validation:
  ZH_Htautau:
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200101.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200102.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200103.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200104.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200105.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200106.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200107.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200108.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200109.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200110.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200111.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200112.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200113.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200114.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200115.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200116.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200117.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200118.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200119.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200120.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200121.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200122.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200123.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200124.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200125.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200126.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200127.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200128.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200129.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200130.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200131.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200132.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200133.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200134.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200135.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200136.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200137.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200138.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200139.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200140.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200141.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200142.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200143.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200144.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200145.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200146.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200147.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200148.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200149.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200150.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200151.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200152.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200153.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200154.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200155.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200156.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200157.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200158.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200159.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200160.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200161.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200162.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200163.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200164.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200165.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200166.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200167.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200168.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200169.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200170.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200171.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200172.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200173.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200174.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200175.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200176.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200177.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200178.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200179.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200180.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200181.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200182.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200183.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200184.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200185.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200186.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200187.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200188.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200189.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200190.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200191.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200192.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200193.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200194.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200195.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200196.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200197.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200198.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200199.parquet
    - 20240402_full_stats/ZH_Htautau/reco_p8_ee_ZH_Htautau_ecm380_200200.parquet
  QCD:
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100101.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100102.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100103.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100104.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100105.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100106.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100107.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100108.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100109.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100110.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100111.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100112.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100113.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100114.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100115.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100116.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100117.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100118.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100119.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100120.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100121.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100122.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100123.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100124.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100125.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100126.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100127.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100128.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100129.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100130.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100131.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100132.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100133.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100134.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100135.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100136.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100137.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100138.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100139.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100140.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100141.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100142.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100143.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100144.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100145.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100146.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100147.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100148.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100149.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100150.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100151.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100152.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100153.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100154.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100155.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100156.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100157.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100158.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100159.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100160.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100161.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100162.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100163.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100164.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100165.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100166.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100167.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100168.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100169.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100170.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100171.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100172.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100173.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100174.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100175.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100176.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100177.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100178.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100179.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100180.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100181.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100182.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100183.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100184.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100185.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100186.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100187.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100188.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100189.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100190.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100191.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100192.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100193.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100194.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100195.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100196.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100197.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100198.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100199.parquet
    - 20240402_full_stats/QCD/reco_p8_ee_qq_ecm380_100200.parquet
